// Code generated by talk gen; DO NOT EDIT.

package main

func (s *userService) TalkAnnotations() map[string]string {
	return map[string]string{
		"HealthCheck": "@talk path=/health method=GET",
		"InternalCheck": "@talk skip",
	}
}
